### ISSUE TITLE
Spawn fails - perhaps cant launch browser

### ISSUE THREAD

**Issue by brucem1976** [vuejs-templates/webpack-simple#110]
So vue-cli init worked fine, and npm install.
Interestingly, I had to still npm install cross-env -g
I am on a chromebook - is it possible that the npm run dev is not allowing the browser to open?

> can-i-ride@1.0.0 dev /home/chronos/user/Downloads/can-i-ride
> cross-env NODE_ENV=development webpack-dev-server --open --hot

internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at spawn (/usr/local/node/lib/node_modules/cross-env/node_modules/cross-spawn/index.js:17:18)
    at crossEnv (/usr/local/node/lib/node_modules/cross-env/dist/index.js:31:38)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/cross-env/dist/bin/cross-env.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! can-i-ride@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
npm ERR! Exit status 1

**Comment by brucem1976** [comment]
Managed to get this running - also had to npm i webpack-dev-server -g and then remove "--open" from dev in package.json

Interesting that I had to do 2 npm installs, and remove --open - I assume it has to do with running on a Chromebook, as it works perfectly on Windows

**Comment by brucem1976** [comment]
Also needed to manually npm install webpack -g ...

**Comment by robdodson** [comment]
I just ran into this too. I think the issue is just that the CLI doesn't run `npm i` for you, so when you cd into the directory and run `npm run dev` there's no modules and it fails. Silly mistake but I was also scratching my head for a second. I guess that's because other CLI's I've used tend to run `npm i` for you. Maybe Vue CLI should consider doing the same?

**Comment by Parka** [comment]
Just deleting --open seemed to work for me.
