### ISSUE TITLE
missing script dev

### ISSUE THREAD

**Issue by sebnet** [vuejs-templates/webpack-simple#118]
When I try to run the command `npm run dev` I get the following error
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\seb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose config Skipping project config: C:\Users\seb/.npmrc. (matches userconfig)
**5 verbose stack Error: missing script: dev**
5 verbose stack     at run (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
5 verbose stack     at C:\Users\seb\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
5 verbose stack     at C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:114:5
5 verbose stack     at C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:401:5
5 verbose stack     at checkBinReferences_ (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:45)
5 verbose stack     at final (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:399:3)
5 verbose stack     at then (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:159:5)
5 verbose stack     at ReadFileContext.<anonymous> (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:331:20)
5 verbose stack     at ReadFileContext.callback (C:\Users\seb\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
6 verbose cwd C:\Users\seb\Documents\vue-cli
7 verbose Windows_NT 10.0.15063
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\seb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
9 verbose node v6.11.1
10 verbose npm  v5.3.0
11 error missing script: dev
12 verbose exit [ 1, true ]

**## OS: Windows 10
node v6.11.1
npm v5.3.0**

**Comment by sebnet** [comment]
​it was my mistake.
I didn't realize that it creates a new directory. When I 'cd' into it, it works perfect.
