### ISSUE TITLE
Failed to exec 'npm run dev' on win7 64bit&&node 6.3.1

### ISSUE THREAD

**Issue by wengang** [vuejs-templates/webpack-simple#16]
13 info lifecycle vuewps@~dev: Failed to exec dev script
14 verbose stack Error: vuewps@ dev: `webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid vuewps@
16 verbose cwd d:\WorkDir\vuewps
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error vuewps@ dev: `webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the vuewps@ dev script 'webpack-dev-server --inline --hot'.

**Comment by wengang** [comment]
bcs the port being used
