### ISSUE TITLE
Mac OSX webpack server not starting

### ISSUE THREAD

**Issue by hregibo** [vuejs-templates/webpack-simple#168]
When starting the `npm run dev` command from a Windows 10 system, all works fine; However, from my Macbook pro, i get this error when doing so:

```
Missing argument values: config, config-name, context, entry, module-bind, module-bind-post, module-bind-pre, output-path, output-filename, output-chunk-filename, output-source-map-filename, output-public-path, output-jsonp-function, output-library, output-library-target, records-input-path, records-output-path, records-path, define, target, watch-aggregate-timeout, devtool, resolve-alias, resolve-extensions, resolve-loader-alias, optimize-max-chunks, optimize-min-chunk-size, prefetch, provide, plugin, open-page
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! udemy1@1.0.0 dev: 'cross-env NODE_ENV=development webpack-dev-server --open --hot'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the udemy1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hugo.xxxxxx/.npm/_logs/2018-01-09T08_07_22_512Z-debug.log
```
Any idea why?

This is a FRESH install from vue-cli.
`vue init webpack-simple udemy1`
using all default values provided for settings

complete log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle udemy1@1.0.0~predev: udemy1@1.0.0
6 info lifecycle udemy1@1.0.0~dev: udemy1@1.0.0
7 verbose lifecycle udemy1@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle udemy1@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/hugo.xxxxxx/Documents/Projets/vue/udemy1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
9 verbose lifecycle udemy1@1.0.0~dev: CWD: /Users/hugo.xxxxxx/Documents/Projets/vue/udemy1
10 silly lifecycle udemy1@1.0.0~dev: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --open --hot' ]
11 silly lifecycle udemy1@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle udemy1@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: udemy1@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid udemy1@1.0.0
15 verbose cwd /Users/hugo.xxxxxx/Documents/Projets/vue/udemy1
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error udemy1@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
22 error Exit status 1
23 error Failed at the udemy1@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by axtho** [comment]
same here

**Comment by axtho** [comment]
It is a webpack 2.9.10 issue. Just pin the version to, say, 2.9.1 and it works.

**Comment by hregibo** [comment]
Locking it to 2.9.1 worked, thanks @axtho
