### ISSUE TITLE
vue init 1.0 throws error

### ISSUE THREAD

**Issue by rdpascua** [vuejs-templates/webpack-simple#18]
```bash
$ vue init webpack-simple#1.0 my-project


/home/user/.npm-global/lib/node_modules/vue-cli/bin/vue-init:130
      var hasDist = JSON.parse(body).some(function (branch) {
                                     ^

TypeError: JSON.parse(...).some is not a function
    at Request._callback (/home/user/.npm-global/lib/node_modules/vue-cli/bin/vue-init:130:38)
    at Request.self.callback (/home/user/.npm-global/lib/node_modules/vue-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/user/.npm-global/lib/node_modules/vue-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/user/.npm-global/lib/node_modules/vue-cli/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by chrisvfritz** [comment]
This is very likely due to using a version of node older than v4, which is not supported by vue-cli. @rdpascua Which version are you using?

**Comment by rdpascua** [comment]
node 6.0, npm 3+ and im using ubuntu 16.04 everything is latest. ive been using vue cli for months now. i don't know what happened

**Comment by chrisvfritz** [comment]
Hmm, then my next guess is some temporary problem with GitHub's API. Is this happening every time you run the command or did it only happen once?

**Comment by emctoo** [comment]
@rdpascua try this: vue init "webpack-simple#1.0" my-project

**Comment by rdpascua** [comment]
Let me check if this resolves the issue, but I've tried that already.

**Comment by chrisvfritz** [comment]
@rdpascua Any word on this?

**Comment by rdpascua** [comment]
I've tried installing using the #1.0 it works.

**Comment by chrisvfritz** [comment]
Yay!

**Comment by aleksvp2017** [comment]
@rdpascua .. it isn't clear for me the solution that worked for you, can you help me out here?
