### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by cx-emerge** [vuejs-templates/webpack-simple#19]
```
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: df1b034b1e5d8233d20f
Version: webpack 2.1.0-beta.21
Time: 5087ms
   Asset     Size  Chunks             Chunk Names
build.js  50.1 kB       0  [emitted]  main

ERROR in ./src/App.vue
Module build failed: /home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/vue-loader/lib/parser.js:25
      output.styles.forEach(style => {
                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/vue-loader/lib/loader.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/vue-loader/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadLoader (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:140:2)
    at runLoaders (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:326:2)
    at NormalModule.doBuild (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/lib/NormalModule.js:125:2)
    at NormalModule.build (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/lib/NormalModule.js:173:15)
    at Compilation.buildModule (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/lib/Compilation.js:127:9)
    at /home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/lib/Compilation.js:303:10
    at /home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/lib/NormalModuleFactory.js:63:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
 @ ./src/main.js 2:0-28
```
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.15.1
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild test@
6 info build test@
7 verbose unsafe-perm in lifecycle true
8 info test@ Failed to exec build script
9 verbose stack Error: test@ build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid test@
11 verbose cwd /home/gaoxiang/projects/lwwl/micro-cms/public/lwwl/front-end/back-end/test
12 error Linux 4.4.0-34-generic
13 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build"
14 error node v4.5.0
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error test@ build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
17 error Exit status 2
18 error Failed at the test@ build script 'cross-env NODE_ENV=production webpack --progress --hide-modules'.
18 error This is most likely a problem with the test package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env NODE_ENV=production webpack --progress --hide-modules
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs test
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls test
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by heyandie** [comment]
i guess the problem is with version of node.js, i was having the same issue until i uninstalled and install the latest version of node

**Comment by cx-emerge** [comment]
yes, vue 2.0+ must use node6 +
