### ISSUE TITLE
Error run npm run dev require(...) is not a function

### ISSUE THREAD

**Issue by danywalls** [vuejs-templates/webpack-simple#81]
I got a error when execute npm run dev on this template, the files for a project template has correctly created, but i got a error when webpack is starting.

I did a test using another template "webpack" and works as charm

[npm-debug.txt](https://github.com/vuejs-templates/webpack-simple/files/818766/npm-debug.txt)

nba@1.0.0 dev /Users/danyparedes/Desktop/nba
> cross-env NODE_ENV=development webpack-dev-server --open --hot

/Users/danyparedes/Desktop/nba/node_modules/cross-env/dist/bin/cross-env.js:4
require('../')(process.argv.slice(2));
              ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/danyparedes/Desktop/nba/node_modules/cross-env/dist/bin/cross-env.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by LinusBorg** [comment]
node & npm version?
