### ISSUE TITLE
"SyntaxError: Unexpected token {" on fresh install

### ISSUE THREAD

**Issue by Metevier** [vuejs-templates/webpack-simple#88]
I'm encountering the same issue with both webpack and webpack-simple.
The issue seems to lie within the loading of the script block as removing it gets rid of the error.
Here is the stack trace:
```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"id":"data-v-53c6d8e7","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue

Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadLoader (C:\Projects\test\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Projects\test\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Projects\test\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"id":"data-v-53c6d8e7","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=
0!./src/App.vue 4:14-272 13:3-17:5 14:22-280
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

Thanks for any advice on this.

**Comment by jayming111** [comment]
i also blocked by this issue,  so can anyone provide a solution?

**Comment by rhinoandre** [comment]
I'm facing this issue too, I've tried to copy the dependencies' versions of the webpack full, but it's still the same.

**Comment by peterjlord** [comment]
I was having this issue as well.  

I upgraded my nodejs from vv4.8.0 to v4 v7.7.3 and works now.

**Comment by rhinoandre** [comment]
Yeah, it's worked for me as well.

**Comment by omahm** [comment]
@peterjlord upgrading nodeJS worked for me, thanks.
